version: "3.8"

services:
  forex-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forex_container
    ports:
      - "8000:8000"
    volumes:
      - ./app/models:/app/models 
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
